title: Oluwatomi Araromi
logo: Headshot.jpeg
description: Data analyst with two years of experience, specializing in report automation using Advanced Excel, data interrogation and manipulation with SQL, and business intelligence reporting with Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
